import numpy as np


LAYERS_SCHEME = [1, 16, 1]
LAYERS_SCHEME_LENGHT = len(LAYERS_SCHEME)

EPOCHS_NB = 50

TRAINING_DATASET_SIZE = 512
TRAINING_DATASET_PERCENTAGE = 0.80
DATASET_SIZE = int(TRAINING_DATASET_SIZE / TRAINING_DATASET_PERCENTAGE)
TESTING_DATASET_SIZE = DATASET_SIZE - TRAINING_DATASET_SIZE

BATCHES_NB = 16
BATCH_SIZE = TRAINING_DATASET_SIZE // BATCHES_NB

WEIGHTS_MEAN = 0.0     # For normal distribution
WEIGHTS_VARIANCE = 2.0 / (LAYERS_SCHEME[0] + LAYERS_SCHEME[-1])     # For normal distribution
WEIGHTS_SEMI_RANGE = np.sqrt(6.0 / (LAYERS_SCHEME[0] + LAYERS_SCHEME[-1]))     # For uniform distribution

BIAS_RANGE_FACTOR = 2.0

LEARNING_RATE = 5e-2     # Eta